name-template: 'v$NEXT_PATCH_VERSION 💎'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'skip-changelog'
template: |
  ## Changes

  $CHANGES 
no-changes-template: 'Changes will arrive soon 😎'
