name-template: 'v$NEXT_PATCH_VERSION 💎'
tag-template: 'v$NEXT_PATCH_VERSION'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
categories:
  - title: 'Breaking changes'
    label: 'breaking-changes'
template: |
  $CHANGES
  
  Thanks to $CONTRIBUTORS! 🎉
no-changes-template: 'Changes will arrive soon 😎'
