name-template: 'v$RESOLVED_VERSION 💎'
tag-template: 'v$RESOLVED_VERSION'
sort-direction: 'ascending'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  minor:
    labels:
      - 'breaking-change'
  patch:
    labels:
      - 'patch'
  default: patch
categories:
  - title: 'Breaking changes'
    label: 'breaking-change'
template: |
  ## Changes
  
  $CHANGES
  
  Thanks again to $CONTRIBUTORS! 🎉
no-changes-template: 'Changes will arrive soon 😎'
